// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:209eeffd-85ba-4621-8b2e-bfeeaf160575",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_mGzgRfZBB",
    "aws_user_pools_web_client_id": "1v9aj6jud0uuibpipjld16f1up",
    "oauth": {},
    "aws_mobile_analytics_app_id": "c12225cc630248f1a4cc6dadefaa8ea7",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "myamplifyproject-20190713144434-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://myamplifyproject-20190713144434-hostingbucket-dev.s3-website-us-east-1.amazonaws.com",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamoa1e627f1-dev",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "api974f738e",
            "endpoint": "https://ogwaf32v5i.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
